const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
const path = require('node:path');

(async () => {
  const date = '2026-09-28';
  const formats = ['Рилс', 'Карусель', 'Пост ТГ', 'Threads'];
  const story = { id: 'preview-stories', date, format: 'Сторис', title: 'Пример: сторис', parts: [{ id: 'part-1', text: 'Текст первой сторис', published: false }, { id: 'part-2', text: 'Текст второй сторис', published: false }] };
  let saved = { schema: 1, items: [story, ...formats.map((format, index) => ({ id: `preview-${index}`, date, format, title: `Пример: ${format}`, parts: [{ id: 'part-1', text: `Текст: ${format}`, published: false }] }))] };
  let revision = 'a'.repeat(32);
  let writes = 0;
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/**', async route => {
    const request = route.request(); const url = new URL(request.url()); const endpoint = url.pathname;
    const json = body => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
    if (endpoint === '/api/auth/me') return json({ user: { id: 'polina-preview', name: 'Полина', authProvider: 'telegram' } });
    if (endpoint === '/api/state/publications') {
      if (request.method() === 'GET') return json({ data: saved, revision });
      if (request.headers()['if-match'] !== revision) return route.fulfill({ status: 409, contentType: 'application/json', body: '{}' });
      saved = request.postDataJSON().data; writes++; revision = String.fromCharCode(97 + Math.min(writes, 20)).repeat(32);
      return json({ ok: true, revision });
    }
    if (endpoint === '/api/state/main') return json({ data: { products: [], topics: [], funnels: [], keywords: [], formats: [], platforms: [], productTypes: [] } });
    return json({ data: null });
  });
  await page.goto('http://127.0.0.1:8080/calendar');
  await page.getByRole('heading', { name: 'Календарь' }).waitFor();
  const onboardingSkip = page.getByRole('button', { name: 'Пропустить' });
  if (await onboardingSkip.waitFor({ timeout: 5000 }).then(() => true).catch(() => false)) await onboardingSkip.click();
  await page.getByText('5 публикаций в этом месяце').waitFor();
  const artifactRoot = process.env.CALENDAR_QA_DIR;
  if (artifactRoot) await page.screenshot({ path: path.join(artifactRoot, 'calendar-month-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'month has horizontal overflow');
  await page.getByRole('button', { name: /28 сентября/ }).click();
  await page.getByText('0 из 5 опубликовано').waitFor();
  if (artifactRoot) await page.screenshot({ path: path.join(artifactRoot, 'calendar-day-mobile.png'), fullPage: true });
  await page.locator('.pub-publication').first().click();
  const firstPart = page.locator('.pub-part').first();
  await firstPart.locator('.pub-part-toggle').click();
  assert.equal(await firstPart.locator('.pub-part-toggle').getAttribute('aria-expanded'), 'true');
  await firstPart.locator('.pub-copy').click();
  await page.getByText('Скопировано').waitFor();
  await firstPart.locator('.pub-part-toggle').dblclick();
  await firstPart.evaluate(element => { if (!element.classList.contains('pub-part-done')) throw new Error('Double tap did not mark the story published'); });
  await firstPart.locator('.pub-part-toggle').dblclick();
  assert.equal(await firstPart.evaluate(element => element.classList.contains('pub-part-done')), false, 'second double tap did not undo publication');
  await firstPart.locator('.pub-part-toggle').dblclick();
  assert.equal(await firstPart.evaluate(element => element.classList.contains('pub-part-done')), true, 'third double tap did not restore publication');
  await firstPart.getByRole('button', { name: 'Изменить' }).click();
  await firstPart.locator('.pub-editor').fill('Мой изменённый текст для сторис.');
  await firstPart.getByRole('button', { name: 'Готово' }).click();
  await page.locator('.pub-app[data-save-state="saved"]').waitFor({ timeout: 10000 });
  assert.ok(writes >= 1, 'nothing saved');
  if (artifactRoot) await page.screenshot({ path: path.join(artifactRoot, 'calendar-publication-mobile.png'), fullPage: true });
  await page.reload();
  await page.getByText('Мой изменённый текст для сторис.').waitFor();
  assert.equal(await page.locator('.pub-part').first().evaluate(element => element.classList.contains('pub-part-done')), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'publication has horizontal overflow');
  await page.getByTitle('Перенести публикацию').click();
  await page.locator('input[type=date]').fill('2026-10-02');
  await page.getByRole('button', { name: 'Перенести', exact: true }).last().click();
  await page.getByText(/2 октября/).first().waitFor();
  await page.locator('.pub-app[data-save-state="saved"]').waitFor({ timeout: 10000 });
  assert.equal(saved.items[0].date, '2026-10-02');
  assert.equal(saved.items.length, 5);
  await page.setViewportSize({ width: 320, height: 700 });
  await page.getByRole('button', { name: /2 октября/ }).first().click();
  await page.getByRole('button', { name: 'Месяц' }).click();
  if (artifactRoot) await page.screenshot({ path: path.join(artifactRoot, 'calendar-month-320.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, '320px month has horizontal overflow');
  assert.deepEqual(errors, []);
  console.log('PASS: five formats, month/day/detail, copy, reversible publication, edit/save/reload, move, mobile overflow, no JS errors. Writes:', writes);
  await browser.close();
})().catch(error => { console.error(error); process.exitCode = 1; });
