import {useState} from 'react';
import type {Funnel} from '@/lib/funnelData';
import {useEditorial} from '@/lib/editorialContext';
import {safeUrl} from '@/lib/assetLinks';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function FunnelRoute({funnel}:{funnel:Funnel}){
 const {data,command,busy}=useEditorial();const current=data?.main.funnels?.find(f=>f.id===funnel.id)||funnel;
 const [open,setOpen]=useState(false),[steps,setSteps]=useState<NonNullable<Funnel['route']>>([]),[error,setError]=useState('');
 return <section><div className="flex justify-between items-center"><h3 className="text-xs font-medium">Путь после кодового слова</h3><Button size="sm" variant="ghost" onClick={()=>{setSteps(structuredClone(current.route||[]));setError('');setOpen(true);}}>Настроить шаги</Button></div>
 {current.route?.length?<ol className="ed-route">{current.route.map((s,i)=><li key={s.id}><span className="ed-badge">{i+1}</span><div>{safeUrl(s.url)?<a className="text-primary text-sm" href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer">{s.label} ↗</a>:<span className="text-sm">{s.label}</span>}{s.note&&<p className="ed-note">{s.note}</p>}{!s.url&&<p className="ed-note">Ссылка ещё не добавлена</p>}</div></li>)}</ol>:<p className="ed-note mb-3">Добавь шаги: сообщение → пост Telegram → PDF → предложение → оплата.</p>}
 <p className="ed-note mb-3">Это схема и ссылки. Автоматическая выдача здесь не включается.</p>
 <Dialog open={open} onOpenChange={v=>{if(!v&&JSON.stringify(steps)!==JSON.stringify(current.route||[])&&!window.confirm('Закрыть без сохранения шагов?'))return;setOpen(v);}}><DialogContent className="ed-small-dialog"><DialogTitle>Шаги воронки · {funnel.keyword}</DialogTitle><DialogDescription>Укажи реальные страницы и файлы, по которым проходит человек.</DialogDescription>{steps.map((s,i)=><div className="border-b pb-2" key={s.id}><label className="ed-label">Шаг {i+1}<input className="ed-input" value={s.label} onChange={e=>setSteps(steps.map(x=>x.id===s.id?{...x,label:e.target.value}:x))}/></label><label className="ed-label">Ссылка<input className="ed-input" type="url" value={s.url} onChange={e=>setSteps(steps.map(x=>x.id===s.id?{...x,url:e.target.value}:x))}/></label><label className="ed-label">Условие или пояснение<input className="ed-input" value={s.note||''} onChange={e=>setSteps(steps.map(x=>x.id===s.id?{...x,note:e.target.value}:x))}/></label><div className="flex gap-2"><Button variant="ghost" disabled={i===0} onClick={()=>{const next=[...steps];[next[i-1],next[i]]=[next[i],next[i-1]];setSteps(next);}}>Выше</Button><Button variant="ghost" onClick={()=>{if(window.confirm('Убрать шаг?'))setSteps(steps.filter(x=>x.id!==s.id));}}>Убрать</Button></div></div>)}<Button variant="outline" onClick={()=>setSteps([...steps,{id:crypto.randomUUID(),label:'',url:''}])}>Добавить шаг</Button>{error&&<p role="alert" className="ed-error">{error}</p>}<Button disabled={busy} onClick={async()=>{try{await command('funnel.route',{id:funnel.id,steps});setOpen(false);}catch(e){setError((e as Error).message);}}}>Сохранить путь</Button></DialogContent></Dialog>
 </section>;
}
